### PR TITLE
use empty to check if not empty array rather than array[0]

### PR DESCRIPTION
**Pull request by joolswills**
fixes error Undefined offset: 0 in app/code/community/TriggeredMessaging/DigitalDataLayer/Model/Page/Observer.php

#7

### CODE REVIEW

**Comment by dhendo** [comment]
Are you happy with the fix in https://github.com/TriggeredMessaging/digitalDataMagentoExtension/pull/8/files#diff-5359358b83cb99324c5652635f8a6246R754 ?

**Comment by joolswills** [comment]
Thanks. Will tet and let you know. You have introduced some whitespace errors in that commit btw.

**Comment by joolswills** [comment]
I would also add, that you need to be sure an array is returned if using count - as an empty string will return 1 - so using !empty as above may be safer.

**Comment by joolswills** [comment]
My mistake btw regarding the commit - I didn't mean to attribute it to you. I think it needs some cleanup before committing though - perhaps you can merge it and then do some cosmetic changes (as well as the change mentioned above) - The existing codebase has some inconsistencies with mixed use of spaces/tabs for indentation and one file that is CRLF line endings cs LF.

**Comment by dhendo** [comment]
@joolswills I've merged @blakefinney 's latest version - he's done some normalisation and code tidy on top of the code change.

**Pull request closed without merging**
